/**
 * @snowpack/plugin-react-refresh (Fast Refresh)
 * Based on details provided by:
 * - https://github.com/facebook/react/issues/16604#issuecomment-528663101
 * - https://github.com/vitejs/vite-plugin-react (see LICENSE)
 */

const fs = require('fs').promises;
const path = require('path');

const main = async () => {
  const reactRefreshLoc = require.resolve('react-refresh/cjs/react-refresh-runtime.development.js');
  const reactRefreshCode = await fs.readFile(reactRefreshLoc, { encoding: 'utf-8' });
  await fs.writeFile(path.join(__dirname, 'runtime.js'), `
// GENERATED BY POSTINSTALL SCRIPT

function debounce(e,t){let u;return()=>{clearTimeout(u),u=setTimeout(e,t)}}
{
  const exports = {};
  ${reactRefreshCode.replace(`process.env.NODE_ENV`, JSON.stringify('development'))}
  exports.performReactRefresh = debounce(exports.performReactRefresh, 30);
  window.$RefreshRuntime$ = exports;
  window.$RefreshRuntime$.injectIntoGlobalHook(window);
  window.$RefreshReg$ = () => {};
  window.$RefreshSig$ = () => (type) => type;
}
`,
  );
};

main();
