name: "Format Code"

on:
  push:
    branches: 
      - master
      
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x" 
      - name: npm install
        run: npm ci --no-optional
        env:
          CI: true
      - name: npm run format
        run: npm run format
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[ci] npm run format"
          branch: ${{ github.head_ref }}
          push_options: --force
