# Inspired by https://bret.io/projects/package-automation/

name: Create Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'what kind of release? (ex: "next", "latest")'
        required: true
      bump:
        description: 'how much to bump? (ex: "patch", "prerelease")'
        required: true
      packagePath:
        description: 'path to package? (ex: "snowpack", "plugins/plugin-babel")'
        required: true

env:
  node_version: 14

jobs:
  version_and_release:
    runs-on: ubuntu-latest
    steps:
      # SETUP:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ env.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node_version }}
          # (REQUIRED) setting a registry enables the NODE_AUTH_TOKEN env variable where we can set an npm token.
          registry-url: 'https://registry.npmjs.org'
      - run: git config --global user.email "github-ci@snowpack.dev"
      - run: git config --global user.name " ${{ github.actor }}"
      - run: yarn --frozen-lockfile

      # PUBLISH:
      - run: node -e "require('./scripts/release.cjs')('${{ github.event.inputs.packagePath }}', '${{ github.event.inputs.tag }}', '${{ github.event.inputs.bump }}')"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
