name: Test Code (Bundled)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: build
        run: |
          yarn --ignore-engines --frozen-lockfile
          yarn build
          yarn bundle
        env:
          CI: true
      - name: test
        run: yarn test
        env:
          CI: true
          NODE_OPTIONS: '--max_old_space_size=4096'
      - name: dev test
        run: yarn test:dev
        if: matrix.os == 'ubuntu-latest'
        env:
          CI: true
          NODE_OPTIONS: '--max_old_space_size=4096'
